### ISSUE TITLE
; Unknown table

### ISSUE THREAD

**Issue by iimarckus** [Drenn1/ages-disasm#1]
```
BDFGHJLM♠♥♦♣#
NQRSTWY!●▲■+-
bdfghj m$*/:~
nqrstwy?%&<=>
23456789↑↓←→@
```

**Comment by Stewmath** [comment]
Ah, the secrets symbols... thanks very much. While I'm at it perhaps I should see about making parseText.py read those special symbols.

**Comment by Stewmath** [comment]
Dealt with in 1c1699cdb004ee467545b40962bae554a0c0ef06.
