### ISSUE TITLE
Seasons' INTERACID_QUICKSAND Documentation

### ISSUE THREAD

**Issue by ZerotoKoops** [Drenn1/ages-disasm#15]
[include/wram.s]:
.ifdef ROM_SEASONS
wPirateSkullRandomNumber: ; $ccc1
; Set to a random number from $01-$04 from var38 of INTERACID_PIRATE_SKULL
; Bit 7 set if INTERACID_QUICKSAND subid matches
; Used to determine whether the right quicksand pit has been found (for the bell)
	db

.else ; ROM_AGES
wcca7: ; $cca7
	db
.endif

[INTERACID_QUICKSAND.txt](https://github.com/Drenn1/oracles-disasm/files/6528005/INTERACID_QUICKSAND.txt)

**Comment by Stewmath** [comment]
I merged this in, thanks!
