### ISSUE TITLE
Documentation Error in code/bank2.s

### ISSUE THREAD

**Issue by ZerotoKoops** [Drenn1/ages-disasm#21]
The documentation above mapMenu_dungeonEntranceText needs to be changed.
; This table changes the text of a tile on a map depending on if a dungeon has been
; entered.
; b0: Room index (if Link's visited this room, use the dungeon's name as the text)
; b1: Bits 0-6: Text index to use if the dungeon hasn't been entered.
;               If it HAS been entered, the index will be $02XX, where XX is the index
;               used for this table's lookup (a dungeon index).
;     Bit 7: 0=group 4, 1=group 5

On the last line, the documentation is backwards. Bit 7 should be 1 for Group 4 and 0 for Group 5.
Please refer to the table, and notice that all Group 4 dungeons have an $80|, as well as the code in @checkDungeonEntered has a jr nz instead of jr z.
Not sure why they coded this way, but please fix documentation.

**Comment by Stewmath** [comment]
Fixed!
