### ISSUE TITLE
SND_UNKNOWN7 is the sound played when healed at a Fairy Fountain

### ISSUE THREAD

**Issue by deathaplenty** [Drenn1/ages-disasm#5]
In [music.s](https://github.com/Drenn1/ages-disasm/blob/master/constants/music.s#L243), this sound is the sound played when you are healed at a fairy fountain. At least, that's what it is in Seasons. I'm not sure if it's the same in Ages.

[Line 243](https://github.com/Drenn1/ages-disasm/blob/master/constants/music.s#L243)
SND_UNKNOWN7            db ; $8c

**Comment by Stewmath** [comment]
I'm a tad late here but thanks lol
